### ISSUE TITLE
Weak but enabled dependency isn't included in graph

### ISSUE THREAD

**Issue by MarijnS95** [EmbarkStudios/krates#50]
**Describe the bug**
Since `cargo-deny 0.13.2`, which [upgraded to `krates 0.12.3`](https://github.com/EmbarkStudios/cargo-deny/compare/0.13.1...0.13.2) we get a strange warning on our repo:

```
warning[license-exception-not-encountered]: license exception was not encountered
  ┌─ laz-license-repro/deny.toml:8:14
  │
8 │     { name = "laz", allow = ["LGPL-2.1"] },
  │              ^^^^^ unmatched license exception
```

The `laz` crate is [`optional=true` included via `las`](https://github.com/gadomski/las-rs/blob/55d5f78586794e0b6f0aea2877f62a9980ae94f7/Cargo.toml#L21-L24), but we enable that feature unconditionally and expect `laz` to be part of the crate graph:

```toml
las = { version = "0.7", features = ["laz"] }
```

**To Reproduce**

Take this `Cargo.toml`:

```toml
[package]
name = "laz-license-repro"
version = "0.1.0"
license = "Apache-2.0"

[dependencies]
# laz = "0.6"
las = { version = "0.7", features = ["laz"] }
```

And this `deny.toml`:
```toml
[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
]
exceptions = [
    { name = "laz", allow = ["LGPL-2.1"] },
]

[[licenses.clarify]]
name = "laz"
expression = "LGPL-2.1"
license-files = [
    # bonus: this crate states `license-file = "COPYING"` but `cargo-deny` insists on using `LICENSE.txt`?
    # { path = "COPYING", hash = 0xc5199cf9 },
    { path = "LICENSE.txt", hash = 0xc5199cf9 },
]
```

Run `cargo-deny` and observe:

```console
$ cargo deny check license
warning[license-exception-not-encountered]: license exception was not encountered
  ┌─ laz-license-repro/deny.toml:8:14
  │
8 │     { name = "laz", allow = ["LGPL-2.1"] },
  │              ^^^^^ unmatched license exception

licenses ok
```

**Expected behavior**
No warnings. And when `laz` would be removed from `license.exceptions` `cargo-deny` **must** complain about `LGPL-2.1` not being allowed.

**Device:**
 - OS: Linux
 - Version: Cargo deny 0.13.2 and up

**Additional context**
Feel free to uncomment `# laz = "0.6"` and observe what `cargo-deny` output we expect when this crate is definitely part of the graph. For example, without the `license.clarify` `cargo-deny` rightfully complains about `error[unlicensed]: laz = 0.6.4 is unlicensed` but it doesn't do that anymore when the crate is transitively included via `las = { version = "0.7", features = ["laz"] }`.
